# Tiki Kitchen Appliances Market Analytics
## Data Quality Check

This notebook audits the quality, completeness, consistency, and validity
of the raw datasets collected from Tiki.

The purpose of this step is to identify data quality issues before
performing data cleaning, exploratory data analysis, and business analysis.

### Datasets
- Product IDs
- Product details
- Product reviews

### Important
This notebook does not modify the raw datasets.

## Steps
1. Setup
2. Load Data
3. Dataset Overview
4. Primary Key & Duplicate Checks
5. Missing Value Checks
6. Data Validity Checks
7. Cross-Dataset Consistency
8. Data Quality Summary

### 1. Setup

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

### 2. Load data

In [2]:
product_ids = pd.read_csv("../data/raw/product_ids.csv")
products = pd.read_csv("../data/raw/crawled_product_data.csv")
reviews = pd.read_csv("../data/raw/comments_data.csv")

print("Product IDs:", product_ids.shape)
print("Products:", products.shape)
print("Reviews:", reviews.shape)

Product IDs: (2001, 1)
Products: (2001, 30)
Reviews: (48649, 10)

### 3. Data Overview
This section provides a high-level overview of the collected datasets,
including row counts, columns, data types, and unique identifiers.

In [3]:
print("Product IDs")
display(product_ids.head())

print("\nProducts")
display(products.head())

print("\nReviews")
display(reviews.head())

Product IDs

   product_id
0      359479
1      368305
2      368309
3      374109
4      392729

Products

,id,sku,product_name,meta_title,short_description,price,list_price,original_price,discount,discount_rate,rating_average,review_count,quantity_sold_text,quantity_sold_value,all_time_quantity_sold,inventory_status,inventory_type,stock_item_qty,stock_item_min_sale_qty,stock_item_max_sale_qty,brand_id,brand_name,brand_slug,seller_id,seller_name,seller_store_id,seller_price,seller_is_best_store,category_id,category_name
0,359479,1839478484680,Máy Đánh Trứng Bluestone HMB-6333S (300W) - Hà...,NaN,Công suất 300W và 6 tốc độMáy Đánh Trứng Blues...,551000,829000,829000,278000,34,4.70,1232,Đã bán 12k,12028.00,12028.00,available,instock,1000.00,1.00,1000.00,18977,Bluestone,bluestone,1.00,Tiki Trading,40395.00,551000.00,False,1882.00,Điện Gia Dụng
1,368305,1898506012998,Nồi Cơm Điện Nắp Rời Sharp KSH-D22V - Màu Ngẫu...,NaN,"Dung tích lớn 2.2L, công suất cao 700WNồi Cơm ...",756000,950000,950000,194000,20,4.50,40,Đã bán 267,267.00,267.00,available,instock,1000.00,1.00,1000.00,19912,Sharp,sharp,1.00,Tiki Trading,40395.00,756000.00,False,1343.00,CHƯƠNG TRÌNH KHUYẾN MẠI KHÁC
2,368309,1898129568186,Nồi Cơm Điện Nắp Rời Sharp KSH-D55V (5L) - Trắ...,NaN,"Thiết kế nắp rời, tiện dụngNồi Cơm Điện Nắp Rờ...",2061000,2600000,2600000,539000,21,4.60,47,Đã bán 248,248.00,248.00,available,instock,1000.00,1.00,1000.00,19912,Sharp,sharp,1.00,Tiki Trading,40395.00,2061000.00,False,1882.00,Điện Gia Dụng
3,374109,1892941762784,Nồi Cơm Điện Cuckoo CR-1021 - 1.8L - Hàng Chín...,NaN,"Thiết kế nhỏ gọn, tinh tế Nồi cơm điện Cuckoo ...",1490000,2310000,2310000,820000,35,4.50,10,Đã bán 69,69.00,69.00,available,instock,1000.00,1.00,1000.00,20439,Cuckoo,cuckoo,1.00,Tiki Trading,40395.00,1490000.00,False,1882.00,Điện Gia Dụng
4,392729,1817659204661,Máy Ép Trái Cây Philips HR1811 (300W) - Trắng ...,NaN,Ống ép kích thước lớnMáy Ép Trái Cây Philips H...,932000,1449000,1449000,517000,36,4.50,371,Đã bán 3k,3608.00,3608.00,available,instock,1000.00,1.00,1000.00,19018,Philips,philips,1.00,Tiki Trading,40395.00,932000.00,False,67132.00,Máy ép nhanh

Reviews

,comment_id,product_id,title,content,rating,thank_count,customer_id,customer_name_hash,purchased_at,created_at
0,14649641,359479,Cực kì hài lòng,Tiki giao hàng rất nhanh. Sớm hơn ngày dự kiến...,5,0,17771638,cust_0079893716,1642834690.00,1642935066
1,13306214,359479,Hài lòng,Sản phẩm đúng quảng cáo. Đóng hàng vào thùng l...,4,0,5665142,cust_720638264d,1636597566.00,1637312250
2,12920434,359479,Cực kì hài lòng,"Tốt hơn hẳn mấy loại 3,4 trăm ngàn rất nhiều l...",5,0,24426085,cust_5ae521e1c9,1635323689.00,1635588458
3,12096324,359479,Không hài lòng,Hàng vừa mở ra đã thấy bung mối hàn trong khi ...,2,0,17955295,cust_92e42fe8ce,1629626139.00,1630758154
4,8470740,359479,Cực kì hài lòng,Sản phẩm có chất lượng tuyệt vời đúng như mô t...,5,5,7178520,cust_cd5b037885,1612889862.00,1615968065

In [4]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2001 non-null   int64
 1   sku                      2001 non-null   int64
 2   product_name             2001 non-null   object
 3   meta_title               0 non-null      float64
 4   short_description        1979 non-null   object
 5   price                    2001 non-null   int64
 6   list_price               2001 non-null   int64
 7   original_price           2001 non-null   int64
 8   discount                 2001 non-null   int64
 9   discount_rate            2001 non-null   int64
 10  rating_average           2001 non-null   float64
 11  review_count             2001 non-null   int64
 12  quantity_sold_text       1150 non-null   object
 13  quantity_sold_value      1150 non-null   float64
 14  all_time_quantity_sold   1154 non-null   float64
 15  inventory_status         2001 non-null   object
 16  inventory_type           2001 non-null   object
 17  stock_item_qty           1993 non-null   float64
 18  stock_item_min_sale_qty  1993 non-null   float64
 19  stock_item_max_sale_qty  1993 non-null   float64
 20  brand_id                 2001 non-null   int64
 21  brand_name               2001 non-null   object
 22  brand_slug               2001 non-null   object
 23  seller_id                1993 non-null   float64
 24  seller_name              1993 non-null   object
 25  seller_store_id          1993 non-null   float64
 26  seller_price             1993 non-null   float64
 27  seller_is_best_store     1993 non-null   object
 28  category_id              1993 non-null   float64
 29  category_name            1993 non-null   object
dtypes: float64(11), int64(9), object(10)
memory usage: 469.1+ KB

In [5]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48649 entries, 0 to 48648
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   comment_id          48649 non-null  int64
 1   product_id          48649 non-null  int64
 2   title               48648 non-null  object
 3   content             22741 non-null  object
 4   rating              48649 non-null  int64
 5   thank_count         48649 non-null  int64
 6   customer_id         48649 non-null  int64
 7   customer_name_hash  48564 non-null  object
 8   purchased_at        48538 non-null  float64
 9   created_at          48649 non-null  int64
dtypes: float64(1), int64(6), object(3)
memory usage: 3.7+ MB

In [6]:
overview = pd.DataFrame({
    "dataset":[
        "products_ids",
        "products",
        "reviews"
    ],
    "rows": [
        len(product_ids),
        len(products),
        len(reviews)
    ],
    "columns":[
        len(product_ids.columns),
        len(products.columns),
        len(reviews.columns)
    ]
})

display(overview)

        dataset   rows  columns
0  products_ids   2001        1
1      products   2001       30
2       reviews  48649       10

### 4. Primary key & Duplicate Check

#### 4.1. Product ID

In [7]:
def check_key(df, column):
    return {
        "total_rows": len(df),
        "missing": df[column].isna().sum(),
        "unique": df[column].nunique(),
        "duplicates": df[column].duplicated().sum()
    }

In [8]:
product_ids_quality = check_key(products,"id")

product_ids_quality

{'total_rows': 2001,
 'missing': np.int64(0),
 'unique': 2001,
 'duplicates': np.int64(0)}

#### 4.2. Product IDs vs Product

In [9]:
source_ids = set(
    product_ids["product_id"]
    .dropna()
    .astype(str)
)

product_data_ids = set(
    products["id"]
    .dropna()
    .astype(str)
)

print("IDs collected:", len(source_ids))
print("IDs in product data:", len(product_data_ids))

print("Missing product data:",
      len(source_ids - product_data_ids))

print("Unexpected product IDs:",
      len(product_data_ids - source_ids))

IDs collected: 2001
IDs in product data: 2001
Missing product data: 0
Unexpected product IDs: 0

#### 4.3. Review ID

In [10]:
review_id_quality = check_key(reviews, "comment_id")

review_id_quality

{'total_rows': 48649,
 'missing': np.int64(0),
 'unique': 48649,
 'duplicates': np.int64(0)}

### 5. Missing value Analysis

In [11]:
def missing_summary(df):
    result = pd.DataFrame({
        "missing_count": df.isna().sum(),
        "missing_pct": df.isna().mean() * 100
    })

    return (
        result
        .sort_values("missing_pct", ascending=False)
    )

product_missing = missing_summary(products)

display(product_missing)

                         missing_count  missing_pct
meta_title                        2001       100.00
quantity_sold_text                 851        42.53
quantity_sold_value                851        42.53
all_time_quantity_sold             847        42.33
short_description                   22         1.10
seller_is_best_store                 8         0.40
seller_id                            8         0.40
seller_name                          8         0.40
seller_store_id                      8         0.40
seller_price                         8         0.40
stock_item_min_sale_qty              8         0.40
stock_item_max_sale_qty              8         0.40
stock_item_qty                       8         0.40
category_id                          8         0.40
category_name                        8         0.40
review_count                         0         0.00
rating_average                       0         0.00
discount_rate                        0         0.00
original_price                       0         0.00
list_price                           0         0.00
product_name                         0         0.00
price                                0         0.00
id                                   0         0.00
sku                                  0         0.00
discount                             0         0.00
inventory_type                       0         0.00
brand_name                           0         0.00
brand_id                             0         0.00
inventory_status                     0         0.00
brand_slug                           0         0.00

In [12]:
display(product_missing[product_missing["missing_count"]>0])

                         missing_count  missing_pct
meta_title                        2001       100.00
quantity_sold_text                 851        42.53
quantity_sold_value                851        42.53
all_time_quantity_sold             847        42.33
short_description                   22         1.10
seller_is_best_store                 8         0.40
seller_id                            8         0.40
seller_name                          8         0.40
seller_store_id                      8         0.40
seller_price                         8         0.40
stock_item_min_sale_qty              8         0.40
stock_item_max_sale_qty              8         0.40
stock_item_qty                       8         0.40
category_id                          8         0.40
category_name                        8         0.40

#### Missing status

In [13]:
def missing_status(pct):
    if pct == 0:
        return "OK"
    elif pct < 1:
        return "Low"
    elif pct < 5:
        return "Moderate"
    else:
        return "High"


product_missing["status"] = (
    product_missing["missing_pct"]
    .apply(missing_status)
)

display(product_missing)

                         missing_count  missing_pct    status
meta_title                        2001       100.00      High
quantity_sold_text                 851        42.53      High
quantity_sold_value                851        42.53      High
all_time_quantity_sold             847        42.33      High
short_description                   22         1.10  Moderate
seller_is_best_store                 8         0.40       Low
seller_id                            8         0.40       Low
seller_name                          8         0.40       Low
seller_store_id                      8         0.40       Low
seller_price                         8         0.40       Low
stock_item_min_sale_qty              8         0.40       Low
stock_item_max_sale_qty              8         0.40       Low
stock_item_qty                       8         0.40       Low
category_id                          8         0.40       Low
category_name                        8         0.40       Low
review_count                         0         0.00        OK
rating_average                       0         0.00        OK
discount_rate                        0         0.00        OK
original_price                       0         0.00        OK
list_price                           0         0.00        OK
product_name                         0         0.00        OK
price                                0         0.00        OK
id                                   0         0.00        OK
sku                                  0         0.00        OK
discount                             0         0.00        OK
inventory_type                       0         0.00        OK
brand_name                           0         0.00        OK
brand_id                             0         0.00        OK
inventory_status                     0         0.00        OK
brand_slug                           0         0.00        OK

### 6. Data Validity Check

##### 6.1. Price

In [14]:
products["price"].describe()

count       2001.00
mean     3168951.19
std      6102262.62
min        29000.00
25%       695000.00
50%      1490000.00
75%      2990000.00
max     85028000.00
Name: price, dtype: float64

In [15]:
invalid_price = products[
    (products["price"] <= 0)
]

print("Invalid price:", len(invalid_price))

Invalid price: 0

##### 6.2. List Price

In [16]:
invalid_list_price = products[
    (products["list_price"] <= 0)
]

print(
    "Invalid list price:",
    len(invalid_list_price)
)

Invalid list price: 0

##### 6.3. Original Price VS Price

In [22]:
price_logic_error = products[
    products["original_price"] < products["price"]
]

print(
    "original price < current price:",
    len(price_logic_error)
)

original price < current price: 0

##### 6.4. Discount

In [18]:
invalid_discount = products[
    (products["discount_rate"] < 0)|
    (products["discount_rate"] > 100)
]

print(
    "Invalid discount:",
    len(invalid_discount)
)

Invalid discount: 0

##### 6.5. Rating

In [19]:
invalid_rating = products[
    (products["rating_average"] < 0) |
    (products["rating_average"] > 5)
]

print(
    "Invalid rating:",
    len(invalid_rating)
)

Invalid rating: 0

In [20]:
invalid_review_count = products[
    products["review_count"] < 0
]

print(
    "Invalid review count:",
    len(invalid_review_count)
)

Invalid review count: 0

In [23]:
invalid_quantity = products[
    products["quantity_sold_value"] < 0
]

print(
    "Invalid quantity sold:",
    len(invalid_quantity)
)

Invalid quantity sold: 0

In [25]:
validity_summary = pd.DataFrame([
    {
        "check": "price > 0",
        "invalid_records": len(
            products[products["price"] <= 0]
        )
    },
    {
        "check": "original_price > 0",
        "invalid_records": len(
            products[products["original_price"] <= 0]
        )
    },
    {
        "check": "original_price >= price",
        "invalid_records": len(
            products[
                products["original_price"] <
                products["price"]
            ]
        )
    },
    {
        "check": "0 <= rating <= 5",
        "invalid_records": len(
            products[
                (products["rating_average"] < 0) |
                (products["rating_average"] > 5)
            ]
        )
    },
    {
        "check": "review_count >= 0",
        "invalid_records": len(
            products[products["review_count"] < 0]
        )
    },
    {
        "check": "quantity_sold >= 0",
        "invalid_records": len(
            products[products["quantity_sold_value"] < 0]
        )
    }
])

display(validity_summary)

                     check  invalid_records
0                price > 0                0
1       original_price > 0                0
2  original_price >= price                0
3         0 <= rating <= 5                0
4        review_count >= 0                0
5       quantity_sold >= 0                0

#### 7. Cross-Dataset Consistency

In [47]:
products_with_reviews = set(
    products.loc[
        products["review_count"] > 0,
        "id"
    ].astype(str)
)

review_product_ids = set(
    reviews["product_id"]
    .dropna()
    .astype(str)
)

print(
    "Products with review_count > 0:",
    len(products_with_reviews)
)

print(
    "Products appearing in review dataset:",
    len(review_product_ids)
)

Products with review_count > 0: 655
Products appearing in review dataset: 636

In [30]:
missing_review_products = (
    products_with_reviews -
    review_product_ids
)

unexpected_review_products = (
    review_product_ids -
    products_with_reviews
)

print(
    "Products expected to have reviews but missing:",
    len(missing_review_products)
)

print(
    "Products with reviews but review_count = 0:",
    len(unexpected_review_products)
)

Products expected to have reviews but missing: 655
Products with reviews but review_count = 0: 48649

In [48]:
crawled_review_counts = (
    reviews
    .groupby("product_id")
    .size()
    .reset_index(name="crawled_review_count")
)

review_quality = products.merge(
    crawled_review_counts,
    left_on="id",
    right_on="product_id",
    how="left"
)

review_quality["crawled_review_count"] = (
    review_quality["crawled_review_count"]
    .fillna(0)
    .astype(int)
)

In [49]:
review_quality[
    [
        "product_id",
        "review_count",
        "crawled_review_count"
    ]
].head(20)

    product_id  review_count  crawled_review_count
0    359479.00          1232                  1245
1    368305.00            40                    48
2    368309.00            47                    59
3    374109.00            10                    17
4    392729.00           371                   400
5    392839.00           236                   265
6    392842.00             3                   170
7    392857.00           130                   155
8    393735.00           438                   465
9    394854.00          1154                  1180
10         NaN             0                     0
11         NaN             0                     0
12   403444.00             1                    30
13         NaN             0                     0
14         NaN             0                     0
15         NaN             0                     0
16         NaN             0                     0
17         NaN             0                     0
18   419160.00             1                    28
19         NaN             0                     0

In [43]:
review_quality["review_crawl_coverage"] = np.where(
    review_quality["review_count"] > 0,
    review_quality["crawled_review_count"] /
    review_quality["review_count"],
    np.nan
)

In [44]:
invalid_review_rating = reviews[
    (reviews["rating"] < 1) |
    (reviews["rating"] > 5)
]

print(
    "Invalid review ratings:",
    len(invalid_review_rating)
)

Invalid review ratings: 0

#### 8. Data Quality Summary

In [46]:
quality_summary = pd.DataFrame([
    {
        "category": "Completeness",
        "check": "Product ID missing",
        "invalid_records": product_ids["product_id"].isna().sum()
    },
    {
        "category": "Uniqueness",
        "check": "Duplicate product IDs",
        "invalid_records": products["id"].duplicated().sum()
    },
    {
        "category": "Consistency",
        "check": "Product IDs missing from product data",
        "invalid_records": len(source_ids - product_data_ids)
    },
    {
        "category": "Consistency",
        "check": "Unexpected product IDs",
        "invalid_records": len(product_data_ids - source_ids)
    },
    {
        "category": "Validity",
        "check": "Invalid prices",
        "invalid_records": len(
            products[products["price"] <= 0]
        )
    },
    {
        "category": "Validity",
        "check": "Invalid ratings",
        "invalid_records": len(
            products[
                (products["rating_average"] < 0) |
                (products["rating_average"] > 5)
            ]
        )
    },
    {
        "category": "Consistency",
        "check": "Products with reviews but missing review data",
        "invalid_records": len(missing_review_products)
    }
])

display(quality_summary)

,category,check,invalid_records
0,Completeness,Product ID missing,0
1,Uniqueness,Duplicate product IDs,0
2,Consistency,Product IDs missing from product data,0
3,Consistency,Unexpected product IDs,0
4,Validity,Invalid prices,0
5,Validity,Invalid ratings,0
6,Consistency,Products with reviews but missing review data,655